[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_solc = true

[doc]
title = "Collar Protocol Documentation"
repository = "https://github.com/CollarNetworks/protocol-core"
out = "docs-temp"