[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.18"

[doc]
title = "Collar Protocol Documentation"
repository = "https://github.com/CollarNetworks/protocol-core"
out = "docs-temp"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
