[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
fs_permissions = [{ access = "read", path = "./"}]
solc_version = "0.8.22"
revert_string = "debug"

[fmt]
line_length = 110
tab_width = 4
int_types = "short"
number_underscore = "thousands"
ignore = ["lib/"]
bracket_spacing = true

[doc]
title = "Collar Protocol Documentation"
repository = "https://github.com/CollarNetworks/protocol-core"
out = "docs-temp"

[fuzz]
runs= 500


[etherscan]
#                   Paste TENDERLY_ACCESS_KEY    Chain ID        Verifier URL: ${TENDERLY_VIRTUAL_TESTNET_RPC}verify/etherscan
unknown_chain = { key = "${TENDERLY_ACCESS_TOKEN}", chain = 137999, url = "${TENDERLY_VIRTUAL_TESTNET_RPC}/verify/etherscan" }
