[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
fs_permissions = [{ access = "read", path = "./"}]

[fmt]
line_length = 160
tab_width = 4
int_types = "long"
number_underscore = "thousands"
ignore = ["lib/"]

[doc]
title = "Collar Protocol Documentation"
repository = "https://github.com/CollarNetworks/protocol-core"
out = "docs-temp"

