name: Tests & Docgen

on: 
  pull_request:
    branches: [main]

env:
  FOUNDRY_PROFILE: ci

jobs:
  test:
    strategy:
      fail-fast: true

    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Check Formatting
        run: forge fmt --check

      - name: Install Dependencies
        run: forge install

      - name: Check Contract Sizes
        run: forge build --sizes

      - name: Check Gas Snapshots
        run: forge snapshot --check

      - name: Run Tests
        run: forge test -vvv
      
      - name: Generate Docs
        run: |
          rm -rf docs
          forge doc --build
          mv docs-temp/book docs

      - name: Commit and Push
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add .
          git commit -m "Auto-Generate Documentation"
          git push