name: Tests

on: [push]

env:
  FOUNDRY_PROFILE: ci

jobs:
  test:
    strategy:
      fail-fast: true
    name: Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.event.pull_request == null
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Check Formatting
        run: forge fmt --check

      - name: Install Dependencies
        run: forge install

      - name: Check Contract Sizes
        run: forge build --sizes

      - name: Check Gas Snapshots
        run: forge snapshot --check

      - name: Run Tests
        run: forge test -vvv