name: Tests

on: [push, pull_request]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Collar Protocol Core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Check Formatting
        run: forge fmt --check

      - name: Install Dependencies
        run: forge install

      - name: Check Contract Sizes
        run: forge build --sizes

      - name: Check Gas Snapshots
        run: forge snapshot --check

      - name: Run Tests
        run: forge test -vvv