name: Tests & Docgen

on: [push, pull_request]

env:
  FOUNDRY_PROFILE: ci

jobs:
  test:
    strategy:
      fail-fast: true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: github.event_name == 'pull_request'
        with:
          fetch-depth: 0
          submodules: recursive
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/checkout@v4
        if: github.event_name == 'push'
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Check Formatting
        run: forge fmt --check

      - name: Install Dependencies
        run: forge install

      - name: Check Contract Sizes
        run: forge build --sizes

      - name: Check Gas Snapshots
        run: forge snapshot --check

      - name: Run Tests
        run: forge test -vvv